module.exports = {
    ManagementCourtRoutes: require("./v1.managementCourt"),
    ManagementTopicRoutes: require("./v1.managementTopic"),
    ManagementTutorRoutes: require("./v1.managementTutor"),
    SubPermissionRoutes: require("./v1.subPermission"),
    EnrollmentRoutes: require("./v1.enrollment"),
    UserRoutes: require("./v1.user"),
    RolRoutes: require("./v1.rol"),
    RolePermissionRoutes: require("./v1.rolePermission"),
    PermissionRoutes: require("./v1.permission"),
    ModalityRoutes: require("./v1.modality"),
    DevelopmentTypeRoutes: require("./v1.developmentType"),
    GroupRoutes: require("./v1.group"),
    InductionPeriodRoutes: require("./v1.inductionPeriod"),
    WorkshopRegistrationRoutes: require("./v1.workshopRegistration"),
};